/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CreatorsRouteImport } from './routes/creators'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as FilmsIndexRouteImport } from './routes/films.index'
import { Route as FilmsSlugRouteImport } from './routes/films.$slug'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsRoute = CreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsIndexRoute = FilmsIndexRouteImport.update({
  id: '/films/',
  path: '/films/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsSlugRoute = FilmsSlugRouteImport.update({
  id: '/films/$slug',
  path: '/films/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/creators': typeof CreatorsRoute
  '/events/$slug': typeof EventsSlugRoute
  '/films/$slug': typeof FilmsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/events/': typeof EventsIndexRoute
  '/films/': typeof FilmsIndexRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/creators': typeof CreatorsRoute
  '/events/$slug': typeof EventsSlugRoute
  '/films/$slug': typeof FilmsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/events': typeof EventsIndexRoute
  '/films': typeof FilmsIndexRoute
  '/news': typeof NewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/creators': typeof CreatorsRoute
  '/events/$slug': typeof EventsSlugRoute
  '/films/$slug': typeof FilmsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/events/': typeof EventsIndexRoute
  '/films/': typeof FilmsIndexRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/creators'
    | '/events/$slug'
    | '/films/$slug'
    | '/news/$slug'
    | '/events/'
    | '/films/'
    | '/news/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/creators'
    | '/events/$slug'
    | '/films/$slug'
    | '/news/$slug'
    | '/events'
    | '/films'
    | '/news'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/creators'
    | '/events/$slug'
    | '/films/$slug'
    | '/news/$slug'
    | '/events/'
    | '/films/'
    | '/news/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CreatorsRoute: typeof CreatorsRoute
  EventsSlugRoute: typeof EventsSlugRoute
  FilmsSlugRoute: typeof FilmsSlugRoute
  NewsSlugRoute: typeof NewsSlugRoute
  EventsIndexRoute: typeof EventsIndexRoute
  FilmsIndexRoute: typeof FilmsIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators': {
      id: '/creators'
      path: '/creators'
      fullPath: '/creators'
      preLoaderRoute: typeof CreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films/': {
      id: '/films/'
      path: '/films'
      fullPath: '/films/'
      preLoaderRoute: typeof FilmsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films/$slug': {
      id: '/films/$slug'
      path: '/films/$slug'
      fullPath: '/films/$slug'
      preLoaderRoute: typeof FilmsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CreatorsRoute: CreatorsRoute,
  EventsSlugRoute: EventsSlugRoute,
  FilmsSlugRoute: FilmsSlugRoute,
  NewsSlugRoute: NewsSlugRoute,
  EventsIndexRoute: EventsIndexRoute,
  FilmsIndexRoute: FilmsIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
